### ISSUE TITLE
Change colors

### ISSUE THREAD

**Issue by SrMonedero** [FirebaseBarcelona/wallaPadel-android#5]
Now that we have new colors from the new logo, we should put them on the rest of the ui.

**Comment by SrMonedero** [comment]
This is my proposal of colors
`<color name="colorPrimary">#04a8ff</color>
<color name="colorPrimaryDark">#0486cc</color>
<color name="colorAccent">#ef6c00</color>`
![screenshot_20160916-102535](https://cloud.githubusercontent.com/assets/2805619/18579804/1fd43eda-7bf8-11e6-8bcb-bd7d5fb37b41.png)
What do you think @jcondominas @juolgon @Jeffarese ?

**Comment by jeffarese** [comment]
I like them :+1:

**Comment by jcondominas** [comment]
Wow, you are a true designer! Lets do it!
